spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5439/url_shortener}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    com.shortener: DEBUG

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}

management:
  endpoints:
    web:
      exposure:
        include: health, info

app:
  cookie:
    secure: false
    domain: ""
    same-site: Lax